# Generated by Django 4.0.6 on 2022-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyamki', '0012_remove_article_content_af_remove_article_content_ar_and_more'),
        ('user', '0002_alter_useravatar_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_articles',
            field=models.ManyToManyField(blank=True, related_name='save_articles', to='nyamki.article', verbose_name='Сохраненные статьи '),
        ),
    ]
