# Generated by Django 4.0.6 on 2022-08-06 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.SlugField()),
                ('image', models.ImageField(upload_to='article/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('draft', models.BooleanField(verbose_name='Черновик')),
                ('number_of_serverings', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество порций')),
                ('unit_of_serverings', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения порции')),
                ('preparation_time', models.FloatField(blank=True, null=True, verbose_name='Время подготовки')),
                ('unit_of_preparation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения подготовки')),
                ('cooking_time', models.FloatField(blank=True, null=True, verbose_name='Время приготовления')),
                ('unit_of_cooking', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения приготовления')),
                ('passive_time', models.FloatField(blank=True, null=True, verbose_name='Пассивное время')),
                ('unit_of_passive', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения пассивного времени')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Типы статей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='Изображение')),
                ('url', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='GroupOfInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.article', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Группа инструкций',
                'verbose_name_plural': 'Группы инструкций',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('calories', models.FloatField(verbose_name='Калории')),
                ('proteins', models.FloatField(verbose_name='Белки')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('fats', models.FloatField(verbose_name='Жиры')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='keyword_image/', verbose_name='Изображение')),
                ('url', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='label_image/', verbose_name='Изображение')),
                ('url', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('in_grams', models.SmallIntegerField(verbose_name='Количество в граммах')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='контент')),
                ('image', models.ImageField(upload_to='instruction/', verbose_name='Изображение')),
                ('group_of_instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.groupofinstructions', verbose_name='Группа инструкций')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.CreateModel(
            name='GroupOfIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.article', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Группа ингредиентов',
                'verbose_name_plural': 'Группы ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='CookingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Количество')),
                ('group_of_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.groupofingredients', verbose_name='Группа ингредиентов')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.ingredient', verbose_name='Ингредиент')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyamki.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецепте',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='article_categories', to='nyamki.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='article_keywords', to='nyamki.keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='article_labels', to='nyamki.label', verbose_name='Метки'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyamki.articletype', verbose_name='Тип статьи'),
        ),
    ]
