# Generated by Django 4.0.6 on 2022-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyamki', '0007_alter_comment_options_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
    ]
