# Generated by Django 4.0.6 on 2022-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyamki', '0013_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='for_article',
            field=models.BooleanField(default=0, verbose_name='Для статей'),
        ),
    ]
