# Generated by Django 4.0.6 on 2022-09-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyamki', '0015_alter_category_for_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingingredient',
            name='value',
            field=models.FloatField(verbose_name='Количество'),
        ),
    ]
