# Generated by Django 4.1 on 2022-09-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyamki', '0017_remove_article_content_ru_remove_article_content_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_cooking_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения приготовления'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_cooking_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения приготовления'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_passive_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения пассивного времени'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_passive_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения пассивного времени'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_preparation_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения подготовки'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_preparation_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения подготовки'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_serverings_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения порции'),
        ),
        migrations.AddField(
            model_name='article',
            name='unit_of_serverings_uk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения порции'),
        ),
        migrations.AddField(
            model_name='articletype',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='articletype',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='cookingingredient',
            name='note_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='cookingingredient',
            name='note_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='groupofingredients',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='groupofingredients',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='groupofinstructions',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='groupofinstructions',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='контент'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='label',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='label',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='label',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='label',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
