services:
  db:
    image: postgres:12.12-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python3 /usr/src/dj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dj
    ports:
      - 8000:8000
    depends_on:
      - db
      
volumes:
  postgres_data: