version: '3.8'

services:
  db:
    image: postgres:12.12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /usr/src/dj/manage.py 0.0.0.0:8000
    volumes:
      - .:/usr/src/dj
    ports:
      - 8000:8000
    depends_on:
      - db
      
volumes:
  postgres_data: